@startuml ConsumerSubscription
MessageConsumer -> ConsumerMessageSubscriber: Subscribe (ConsumerId, ChannelId, HashedSecret)
ConsumerMessageSubscriber -> ConsumerStore: Verify Consumer (ConsumerId)
alt Refute
    ConsumerStore --> ConsumerMessageSubscriber: Unknown Consumer (ConsumerId)
    ConsumerMessageSubscriber --> MessageConsumer: SubscriptionFailed (FailureCode)
end
ConsumerStore --> ConsumerMessageSubscriber: Known Consumer (ConsumerId)
ConsumerMessageSubscriber -> ChannelStore: Verify Channel (ChannelId)
alt Refute
    ChannelStore --> ConsumerMessageSubscriber: Unknown Channel (ChannelId)
    ConsumerMessageSubscriber --> MessageConsumer: SubscriptionFailed (FailureCode)
end
ChannelStore --> ConsumerMessageSubscriber: Known Channel (ChannelId)
ConsumerMessageSubscriber -> ConsumerStore: Get Consumer Details (ConsumerId, ChannelId)
ConsumerStore --> ConsumerMessageSubscriber: Consumer Details (StoredHashedSecret)
ConsumerMessageSubscriber -> Auth: Authenticate (ConsumerId, ChannelId, HashedSecret, StoredHashedSecret)
alt Inauthentic
    Auth --> ConsumerMessageSubscriber: Unauthorised (ConsumerId, ChannelId)
    ConsumerMessageSubscriber --> MessageConsumer: SubscriptionFailed (FailureCode)
end
Auth --> ConsumerMessageSubscriber: Authorised (ConsumerId, ChannelId, AuthToken)
ConsumerMessageSubscriber -> ConsumerStore: Update Consumer (ConsumerId, ChannelId, AuthToken)
ConsumerStore --> ConsumerMessageSubscriber: Consumer Details (ConsumerId, ChannelId, StoredAuthToken, ConsumerMessageQueueId)
ConsumerMessageSubscriber -> ConsumerMessageQueue: Verify Consumer Message Queue (ConsumerMessageQueueId)
alt Refute
    ConsumerMessageQueue --> ConsumerMessageSubscriber: No Consumer Message Queue (ConsumerMessageQueueId)
    ConsumerMessageSubscriber -> ConsumerMessageQueue: Build Consumer Message Queue (ConsumerMessageQueueId)
    ConsumerMessageQueue --> ConsumerMessageSubscriber: Message Queue Created (ConsumerMessageQueueId)
end
ConsumerMessageQueue --> ConsumerMessageSubscriber: Known Consumer Message Queue (ConsumerMessageQueueId)
ConsumerMessageSubscriber --> MessageConsumer: Subscribed (ConsumerMessageQueueId, StoredAuthToken)
@enduml