@startuml architecture_overview

MessageConsumer -> ConsumerMessageSubscriber: Receive ( SubscriptionMessage [ConsumerId, AuthToken, Channel] )
ConsumerMessageSubscriber -> Auth: IsAuthenticated (ConsumerId, AuthToken)
alt True
    Auth --> ConsumerMessageSubscriber: Is Authenticated (ConsumerId)
    ConsumerMessageSubscriber -> ConsumerMessageQueue: Dequeue (SubscriptionMessage)
    ConsumerMessageQueue --> ConsumerMessageSubscriber: Message
    ConsumerMessageSubscriber --> MessageConsumer: Message
else False
    Auth --> ConsumerMessageSubscriber: Is Not Authenticated  (ConsumerId)
    ConsumerMessageSubscriber -> MessageConsumer: Request Authentication (ConsumerId, PublicEncryptionKey)
    MessageConsumer -> Auth: Authenticate (ConsumerId, EncryptedPassphrase)
    Auth -> ConsumerStore: Verify (ConsumerId)
    alt Known Consumer
        ConsumerStore --> Auth: Known Consumer (ConsumerId)
        Auth --> MessageConsumer: AuthToken (ConsumerId)
    else Unknown Consumer
        ConsumerStore --> Auth: Unknown Consumer (ConsumerId)
        Auth --> MessageConsumer: Unauthorised
    end
end

@enduml