// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package httpcontainer

import (
	"github.com/google/uuid"
	"pulsyflux/shared"
)

// Injectors from wire.go:

func InitialiseHttpServer(protocol shared.URIProtocol, host shared.URIHost, port shared.URIPort, path shared.URIPath) shared.HttpServer {
	uri := shared.NewUri(protocol, host, port, path)
	readTimeDuration := newDefaultReadTimeoutDuration()
	writeTimeDuration := newDefaultWriteTimeoutDuration()
	idleConnTimeoutDuration := newDefaultServerIdleConnTimeoutDuration()
	responseTimeoutDuration := newDefaultServerResponseTimeoutDuration()
	httpcontainerMaxHeaderBytes := newDefaultHttpMaxHeaderBytes()
	sharedHttpReqHandler := newHttpReqHandler()
	sharedHttpServer := newHttpServer(uri, readTimeDuration, writeTimeDuration, idleConnTimeoutDuration, responseTimeoutDuration, httpcontainerMaxHeaderBytes, sharedHttpReqHandler)
	return sharedHttpServer
}

func InitialiseHttpResHandler(msgId uuid.UUID, successStatusCode int) shared.HttpResHandler {
	sharedHttpStatus := newHttpStatus(successStatusCode)
	sharedMsgId := newHttpMsgId(msgId)
	sharedHttpResHandler := newHttpResHandler(sharedHttpStatus, sharedMsgId)
	return sharedHttpResHandler
}

func InitialiseHttpReq() shared.HttpReq {
	requestTimeoutDuration := newDefaultClientRequestTimeoutDuration()
	requestHeadersTimeoutDuration := newDefaultClientRequestHeadersTimeoutDuration()
	idleConnTimeoutDuration := newDefaultClientIdleConnTimeoutDuration()
	sharedHttpReq := newHttpReq(requestTimeoutDuration, requestHeadersTimeoutDuration, idleConnTimeoutDuration)
	return sharedHttpReq
}
