// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package httpcontainer

import (
	"github.com/google/uuid"
	"pulsyflux/contracts"
	"time"
)

// Injectors from wire.go:

func InitialiseHttpServer(protocol2 protocol, host2 host, port2 port, path2 path) contracts.HttpServer {
	httpcontainerUri := &uri{
		protocol: protocol2,
		host:     host2,
		path:     path2,
		port:     port2,
	}
	readTimeDuration := newDefaultReadTimeoutDuration()
	writeTimeDuration := newDefaultWriteTimeoutDuration()
	idleConnTimeoutDuration := newDefaultIdleConnTimeoutDuration()
	httpcontainerMaxHeaderBytes := newDefaultHttpMaxHeaderBytes()
	contractsHttpReqHandler := newHttpReqHandler()
	contractsHttpServer := newHttpServer(httpcontainerUri, readTimeDuration, writeTimeDuration, idleConnTimeoutDuration, httpcontainerMaxHeaderBytes, contractsHttpReqHandler)
	return contractsHttpServer
}

func InitialiseHttpResHandler(msgUd uuid.UUID, successStatusCode int) contracts.HttpResHandler {
	contractsHttpStatus := newHttpStatus(successStatusCode)
	msgId := newHttpMsgId(msgUd)
	contractsHttpResHandler := newHttpResHandler(contractsHttpStatus, msgId)
	return contractsHttpResHandler
}

func InitialiseHttpReq(idleConTimeout time.Duration) contracts.HttpReq {
	idleConnTimeoutDuration := newDefaultIdleConnTimeoutDuration()
	contractsHttpReq := newHttpReq(idleConnTimeoutDuration)
	return contractsHttpReq
}
