// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package httpcontainer

import (
	"github.com/google/uuid"
	"pulsyflux/shared"
)

// Injectors from wire.go:

func InitialiseHttpServer(protocol uriProto, host uriHost, port uriPort, path uriPath) shared.HttpServer {
	httpcontainerUri := &uri{
		protocol: protocol,
		host:     host,
		path:     path,
		port:     port,
	}
	readTimeDuration := newDefaultReadTimeoutDuration()
	writeTimeDuration := newDefaultWriteTimeoutDuration()
	idleConnTimeoutDuration := newDefaultServerIdleConnTimeoutDuration()
	responseTimeoutDuration := newDefaultServerResponseTimeoutDuration()
	httpcontainerMaxHeaderBytes := newDefaultHttpMaxHeaderBytes()
	sharedHttpReqHandler := newHttpReqHandler()
	sharedHttpServer := newHttpServer(httpcontainerUri, readTimeDuration, writeTimeDuration, idleConnTimeoutDuration, responseTimeoutDuration, httpcontainerMaxHeaderBytes, sharedHttpReqHandler)
	return sharedHttpServer
}

func InitialiseHttpResHandler(msgUd uuid.UUID, successStatusCode int) shared.HttpResHandler {
	sharedHttpStatus := newHttpStatus(successStatusCode)
	msgId := newHttpMsgId(msgUd)
	sharedHttpResHandler := newHttpResHandler(sharedHttpStatus, msgId)
	return sharedHttpResHandler
}

func InitialiseHttpReq() shared.HttpReq {
	requestTimeoutDuration := newDefaultClientRequestTimeoutDuration()
	requestHeadersTimeoutDuration := newDefaultClientRequestHeadersTimeoutDuration()
	idleConnTimeoutDuration := newDefaultClientIdleConnTimeoutDuration()
	sharedHttpReq := newHttpReq(requestTimeoutDuration, requestHeadersTimeoutDuration, idleConnTimeoutDuration)
	return sharedHttpReq
}

func InitialiseHttpReq2() shared.HttpReq {
	requestTimeoutDuration := newDefaultClientRequestTimeoutDuration()
	requestHeadersTimeoutDuration := newDefaultClientRequestHeadersTimeoutDuration()
	idleConnTimeoutDuration := newDefaultClientIdleConnTimeoutDuration()
	sharedHttpReq := newHttpReq(requestTimeoutDuration, requestHeadersTimeoutDuration, idleConnTimeoutDuration)
	return sharedHttpReq
}
