// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package msgbuscontainer

import (
	"github.com/google/uuid"
	"pulsyflux/httpcontainer"
	"pulsyflux/shared"
)

// Injectors from wire.go:

func InitialiseMsgBus(protocol shared.URIProtocol, host shared.URIHost, port shared.URIPort, path shared.URIPath, channelId uuid.UUID, successStatusCode int) shared.MsgBus {
	uri := shared.NewUri(protocol, host, port, path)
	sharedChannel := newChannel(channelId, uri)
	httpResHandler := httpcontainer.InitialiseHttpResHandler(channelId, successStatusCode)
	httpReq := httpcontainer.InitialiseHttpReq()
	sharedMsgBus := newMsgBus(uri, sharedChannel, httpResHandler, httpReq)
	return sharedMsgBus
}
